### ISSUE TITLE
Steps to deploy client not present in Readme.md

### ISSUE THREAD

**Issue by nabinkhadka** [gtalarico/flask-vuejs-template#6] opened 2018-02-01 17:28 UTC
Please include how we can deploy client in heroku

**Comment by gtalarico** [comment] 2018-02-01 17:44
https://github.com/gtalarico/flask-vuejs-template#heroku-deployment
Is there anything missing from this?

**Comment by nabinkhadka** [comment] 2018-02-02 01:50
This does not help for client.

**Comment by gtalarico** [comment] 2018-02-02 02:28
You will need to be more specific than that.

What have you tried? 
Are you getting any errors? 
Did you run `npm run build ` and pushed the build.js to github?

**Comment by gtalarico** [comment] 2018-02-05 01:25
Closing this for now. I can reopen you have additional information to add, but as of now I don't understand what the issue is or what you are asking for.

Steps to run local development server are detailed here:
https://github.com/gtalarico/flask-vuejs-template#running-application-local-development-server

**Closed by gtalarico** 2018-02-05 01:25 UTC
